# 这是一个示例 mods.toml 文件。它包含了与加载模组相关的数据。
# 其中有几个必填字段（#mandatory），以及许多可选字段（#optional）。
# 整体格式符合 TOML v0.5.0 标准。
# 请注意，此文件中包含几个 TOML 列表。
# 可在此处找到有关 TOML 格式的更多信息：https://github.com/toml-lang/toml

# 要加载的模组加载器类型的名称 - 对于常规的 FML @Mod 模组，应为 javafml
modLoader="javafml" #必填

# 与上述模组加载器匹配的版本范围 - 对于常规的 FML @Mod，它将是 Forge 版本
loaderVersion="1.20.1" #必填 这个通常会在每个 Minecraft 版本更新时由 Forge 调整。请查看我们的下载页面以获取版本列表。

# 你的模组的许可证。这是必填的元数据，有助于更好地理解你的再分发权限。
# 你可以在 https://choosealicense.com/ 查看可用的许可证选项。"All rights reserved"（保留所有权利）是默认的版权立场，因此这里默认采用此选项。
license="MIT"

# 发生问题时可以让用户参考的 URL
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #可选

# 模组列表 - 允许的数量取决于具体的模组加载器
[[mods]] #必填

# 模组的 modid
modId="mxt_unplacable_torch" #必填

# 模组的版本号
version="1.0.0" #必填

# 模组的显示名称
displayName="MXTools:Unplacable torch" #必填

# 查询此模组更新的 URL。请参阅 JSON 更新规范：https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #可选

# 在模组 UI 中显示的 "主页" URL
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #可选

# 在模组 JAR 文件根目录中的标志文件名，用于显示
#logoFile="examplemod.png" #可选

# 在模组 UI 中显示的文本字段
#credits="" #可选

# 在模组 UI 中显示的文本字段
authors="${mod_authors}" #可选

# 显示测试控制了服务器连接屏幕中模组的显示方式
# MATCH_VERSION 表示如果客户端和服务器的模组版本不同，则会显示红色 X。这是默认行为，如果你的模组包含服务器和客户端元素，应该选择此项。
# IGNORE_SERVER_VERSION 表示如果模组仅存在于服务器但不存在于客户端，则不会显示红色 X。如果你的模组仅适用于服务器，应使用此选项。
# IGNORE_ALL_VERSION 表示无论模组存在于客户端还是服务器，都不会显示红色 X。这是一个特殊情况，仅适用于不包含服务器组件的模组。
# NONE 表示你的模组未设置任何显示测试，你需要自行定义。详情请参考 IExtensionPoint.DisplayTest。
# 重要说明：这 **不是** 指定模组加载环境（客户端或独立服务器）的指令。你的模组应该在发现自己所处的环境时自行决定如何运行（可能是无操作）。
#displayTest="MATCH_VERSION" # 如果未指定，则 MATCH_VERSION 是默认值 (#可选)

# 模组的描述文本（可多行！）（#必填）
description='''${mod_description}'''

[[dependencies.mxt_unplacable_torch]]
modId="forge"
mandatory=true
versionRange="[43.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.mxt_unplacable_torch]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"


# 功能特性是游戏环境的特定属性，你可能希望声明你的模组需要它们。例如，此示例声明
# 你的模组需要 OpenGL 版本 3.2 或更高版本。其他特性将在未来加入。它们是区分环境的，因此声明此项不会
# 阻止你的模组在服务器上加载。
#[features.${mod_id}]
#openGLVersion="[3.2,)"